# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protofile.messaging.proto.messaging_v2_pb2 as messaging__v2__pb2


class MessagingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.textMessaging = channel.unary_unary(
                '/MessagingService/textMessaging',
                request_serializer=messaging__v2__pb2.MessageRequest.SerializeToString,
                response_deserializer=messaging__v2__pb2.MessageResponse.FromString,
                )
        self.clearMessageHistory = channel.unary_unary(
                '/MessagingService/clearMessageHistory',
                request_serializer=messaging__v2__pb2.ClearHistoryRequest.SerializeToString,
                response_deserializer=messaging__v2__pb2.Empty.FromString,
                )


class MessagingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def textMessaging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def clearMessageHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'textMessaging': grpc.unary_unary_rpc_method_handler(
                    servicer.textMessaging,
                    request_deserializer=messaging__v2__pb2.MessageRequest.FromString,
                    response_serializer=messaging__v2__pb2.MessageResponse.SerializeToString,
            ),
            'clearMessageHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.clearMessageHistory,
                    request_deserializer=messaging__v2__pb2.ClearHistoryRequest.FromString,
                    response_serializer=messaging__v2__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MessagingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessagingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def textMessaging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MessagingService/textMessaging',
            messaging__v2__pb2.MessageRequest.SerializeToString,
            messaging__v2__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def clearMessageHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MessagingService/clearMessageHistory',
            messaging__v2__pb2.ClearHistoryRequest.SerializeToString,
            messaging__v2__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
