# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging_v2.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12messaging_v2.proto\"\x07\n\x05\x45mpty\"4\n\x0eMessageRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"s\n\x0fMessageResponse\x12\r\n\x05input\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x1c\n\x14output_building_info\x18\x03 \x01(\t\x12\x13\n\x0boutput_info\x18\x04 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\t\"(\n\x13\x43learHistoryRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t2{\n\x10MessagingService\x12\x32\n\rtextMessaging\x12\x0f.MessageRequest\x1a\x10.MessageResponse\x12\x33\n\x13\x63learMessageHistory\x12\x14.ClearHistoryRequest\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_v2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_MESSAGEREQUEST']._serialized_start=31
  _globals['_MESSAGEREQUEST']._serialized_end=83
  _globals['_MESSAGERESPONSE']._serialized_start=85
  _globals['_MESSAGERESPONSE']._serialized_end=200
  _globals['_CLEARHISTORYREQUEST']._serialized_start=202
  _globals['_CLEARHISTORYREQUEST']._serialized_end=242
  _globals['_MESSAGINGSERVICE']._serialized_start=244
  _globals['_MESSAGINGSERVICE']._serialized_end=367
# @@protoc_insertion_point(module_scope)
