OPENAI = "OPENAI"
HUGGING_FACE = "HUGGING_FACE"
GEMINI = "GEMINI"
BUILDINGS_COLLECTION_NAME = "Buildings"
BUILDING_CHUNKS_COLLECTION_NAME = "BuildingChunks"
RETRIEVE_BOARDING_HOUSES_OR_BUILDINGS = "RETRIEVE_BOARDING_HOUSES_OR_BUILDINGS"
SHOW_MAP_AND_DIRECTIONS = "SHOW_MAP_AND_DIRECTIONS"
GIVE_AND_EXPLAIN_THE_IMPLIED_BUILDING_DETAILS = (
    "GIVE_AND_EXPLAIN_THE_IMPLIED_BUILDING_DETAILS"
)
COMPARE_BETWEEN_BUILDINGS = "COMPARE_BETWEEN_BUILDINGS"
SAVE_BUILDINGS_TO_THE_SYSTEM = "SAVE_BUILDINGS_TO_THE_SYSTEM"
REPLY_VAGUE_CONVERSATION = "REPLY_VAGUE_CONVERSATION"
REPLY_CASUAL_CONVERSATION = "REPLY_CASUAL_CONVERSATION"
