OPENAI = "OPENAI"
HUGGING_FACE = "HUGGING_FACE"
GEMINI = "GEMINI"
BUILDINGS_COLLECTION_NAME = "Buildings"
BUILDING_CHUNKS_COLLECTION_NAME = "BuildingChunks"
RETRIEVE_BOARDING_HOUSES_OR_BUILDINGS = "RETRIEVE_BOARDING_HOUSES_OR_BUILDINGS"
GIVE_AND_EXPLAIN_THE_IMPLIED_BUILDING_DETAILS = (
    "GIVE_AND_EXPLAIN_THE_IMPLIED_BUILDING_DETAILS"
)
COMPARE_BETWEEN_BUILDINGS = "COMPARE_BETWEEN_BUILDINGS"
ASK_TO_SAVE_BUILDINGS_TO_THE_SYSTEM = "ASK_TO_SAVE_BUILDINGS_TO_THE_SYSTEM"
VAGUE = "VAGUE"
CASUAL_CONVERSATION = "CASUAL_CONVERSATION"
