from enum import Enum

class ToolType(Enum):
    SEARCH_SPECIFIC_LOCATION = "SEARCH_SPECIFIC_LOCATION"
    SEARCH_POINT_OF_INTEREST = "SEARCH_POINT_OF_INTEREST"
    SAVE_LOCATION = "SAVE_LOCATION"
    GET_DIRECTION = "GET_DIRECTION"