from enum import Enum

class ToolType(Enum):
    SEARCH_BUILDING = "SEARCH_BUILDING"
    SEARCH_POINT_OF_INTEREST = "SEARCH_POINT_OF_INTEREST"
    SAVE_BUILDING = "SAVE_BUILDING"
    GET_DIRECTION = "GET_DIRECTION"