""" Environment Variable
"""

import os

IN_DEVELOPMENT = bool(str(os.getenv("IN_DEVELOPMENT")))
LOG_VERBOSE = bool(str(os.getenv("LOG_VERBOSE")))
INSECURE_PORT = str(os.getenv("INSECURE_PORT"))

LLM_USED = str(os.getenv("LLM_USED"))
USE_MODULE = str(os.getenv("USE_MODULE"))
MODULE_USED = str(os.getenv("MODULE_USED"))

WEAVIATE_SECURE = bool(os.getenv("WEAVIATE_SECURE"))
WEAVIATE_REST_HOST = str(os.getenv("WEAVIATE_REST_HOST"))
WEAVIATE_REST_PORT = int(os.getenv("WEAVIATE_REST_PORT"))
WEAVIATE_GRPC_HOST = str(os.getenv("WEAVIATE_GRPC_HOST"))
WEAVIATE_GRPC_PORT = int(os.getenv("WEAVIATE_GRPC_PORT"))

GEMINI_MODEL = str(os.getenv("GEMINI_MODEL"))
GEMINI_TRANSFORMERS_MODEL = str(os.getenv("GEMINI_TRANSFORMERS_MODEL"))
GEMINI_API_KEY = str(os.getenv("GEMINI_API_KEY"))
GOOGLE_MAPS_API_KEY = str(os.getenv("GOOGLE_MAPS_API_KEY"))

HUGGINGFACE_MODEL = str(os.getenv("HUGGINGFACE_MODEL"))
HUGGINGFACE_TRANSFORMERS_MODEL = str(os.getenv("HUGGINGFACE_TRANSFORMERS_MODEL"))

OPENAI_MODEL = str(os.getenv("OPENAI_MODEL"))
OPENAI_ANALYZER_MODEL = str(os.getenv("OPENAI_ANALYZER_MODEL"))
OPENAI_GENERATIVE_MODEL = str(os.getenv("OPENAI_GENERATIVE_MODEL"))
OPENAI_TRANSFORMERS_MODEL = str(os.getenv("OPENAI_TRANSFORMERS_MODEL"))
OPENAI_API_KEY = str(os.getenv("OPENAI_API_KEY"))
OPENAI_ORGANIZATION_ID = str(os.getenv("OPENAI_ORGANIZATION_ID"))

ADVERTISING_PIC_NUMBER = str(os.getenv("ADVERTISING_PIC_NUMBER"))
SERVICE_PIC_NUMBER = str(os.getenv("SERVICE_PIC_NUMBER"))